import {
  Entity,
  PrimaryGeneratedColumn,
  Column,
  CreateDateColumn,
  Index,
} from 'typeorm';

/**
 * Thread-based communication on an order.
 * Replaces the single `notes` field with a full conversation visible to both
 * pharmacy admin and supplier admin. Immutable once created.
 */
@Entity('order_comments')
@Index(['orderId', 'createdAt'])
export class OrderComment {
  @PrimaryGeneratedColumn('uuid')
  id: string;

  @Column({ type: 'uuid' })
  orderId: string;

  @Column({ type: 'uuid' })
  authorId: string;

  /** Role determines which side the comment bubble appears on in the UI */
  @Column({ type: 'varchar', length: 30 })
  authorRole: 'pharmacy_admin' | 'supplier_admin' | 'system_admin';

  @Column({ type: 'varchar', length: 255, nullable: true })
  authorName: string;

  @Column({ type: 'text' })
  body: string;

  /** True if this comment was auto-generated by the system (status change reason, etc.) */
  @Column({ type: 'boolean', default: false })
  isSystemMessage: boolean;

  @CreateDateColumn()
  createdAt: Date;
}
