import { Injectable, Logger } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import * as nodemailer from 'nodemailer';

/**
 * Email delivery via AWS SES in production, or console-log in development.
 *
 * SES setup (one-time):
 *   1. Verify domain in SES console
 *   2. Set SMTP credentials in Secrets Manager
 *   3. Request production access (removes sandbox 24h delay)
 *
 * Template philosophy: plain, professional HTML — no heavy frameworks.
 * Healthcare users trust clarity over design.
 */
@Injectable()
export class NotificationEmailService {
  private readonly logger = new Logger(NotificationEmailService.name);
  private transporter: nodemailer.Transporter;
  private readonly fromAddress: string;
  private readonly isProd: boolean;

  constructor(private readonly config: ConfigService) {
    this.isProd = config.get('NODE_ENV') === 'production';
    this.fromAddress = config.get('EMAIL_FROM', 'noreply@medipulse.ai');

    if (this.isProd) {
      this.transporter = nodemailer.createTransport({
        host:   config.get('SMTP_HOST', 'email-smtp.eu-west-1.amazonaws.com'),
        port:   config.get<number>('SMTP_PORT', 465),
        secure: true,
        auth: {
          user: config.get('SMTP_USER'),
          pass: config.get('SMTP_PASS'),
        },
      });
    } else {
      // Development: log to console only — no emails sent
      this.transporter = nodemailer.createTransport({ jsonTransport: true });
    }
  }

  async send(to: string, subject: string, html: string): Promise<void> {
    if (!to) return;
    try {
      const info = await this.transporter.sendMail({
        from: `MediPulse <${this.fromAddress}>`,
        to,
        subject,
        html,
      });
      if (!this.isProd) {
        this.logger.log(`[DEV] Email to ${to}: "${subject}"`);
      }
    } catch (err: any) {
      this.logger.error(`Email send failed to ${to}: ${err.message}`);
    }
  }

  // ── Email templates ────────────────────────────────────────────────────────

  buildHighRiskStockout(productName: string, stockDays: number, tenantName: string): { subject: string; html: string } {
    return {
      subject: `⚠️ Critical Stock Alert: ${productName} — ${stockDays} days remaining`,
      html: this.wrap(`
        <h2 style="color:#dc2626">Critical Stock Alert</h2>
        <p>Hello ${tenantName},</p>
        <p>
          <strong>${productName}</strong> has only <strong>${stockDays} day${stockDays !== 1 ? 's' : ''}</strong>
          of stock remaining based on current demand.
        </p>
        <p>A procurement draft has been automatically prepared for your review.</p>
        <a href="${this.appUrl()}/pharmacy/queue" style="${this.btnStyle('red')}">
          Review Draft Now →
        </a>
        <p style="color:#6b7280;font-size:12px;margin-top:24px">
          This alert was generated by MediPulse's AI risk engine.
        </p>
      `),
    };
  }

  buildOrderStatusChanged(orderId: string, status: string, productSummary: string, isSupplier: boolean): { subject: string; html: string } {
    const role = isSupplier ? 'supplier' : 'pharmacy';
    return {
      subject: `Order Update: ${status.toUpperCase()} — ${productSummary}`,
      html: this.wrap(`
        <h2 style="color:#1d4ed8">Order Status Update</h2>
        <p>Order <strong>#${orderId.slice(0, 8)}</strong> has been updated to
        <strong style="text-transform:uppercase">${status}</strong>.</p>
        <p>${productSummary}</p>
        <a href="${this.appUrl()}/${role}/orders" style="${this.btnStyle('blue')}">
          View Order →
        </a>
      `),
    };
  }

  buildDeliveryConfirmed(orderRef: string, tenantName: string): { subject: string; html: string } {
    return {
      subject: `✅ Delivery Confirmed — Order #${orderRef}`,
      html: this.wrap(`
        <h2 style="color:#16a34a">Delivery Confirmed</h2>
        <p>Hello ${tenantName},</p>
        <p>Order <strong>#${orderRef}</strong> has been delivered and your inventory has been updated automatically.</p>
        <a href="${this.appUrl()}/pharmacy/orders" style="${this.btnStyle('green')}">
          View Inventory →
        </a>
      `),
    };
  }

  buildDraftCreated(productName: string, qty: number, supplierName: string): { subject: string; html: string } {
    return {
      subject: `📋 Procurement Draft Ready: ${productName}`,
      html: this.wrap(`
        <h2 style="color:#7c3aed">Procurement Draft Prepared</h2>
        <p>MediPulse has automatically prepared a procurement draft for your review:</p>
        <ul>
          <li><strong>Product:</strong> ${productName}</li>
          <li><strong>Quantity:</strong> ${qty} units</li>
          <li><strong>Supplier:</strong> ${supplierName}</li>
        </ul>
        <p>Review and approve with one click in the Procurement Queue.</p>
        <a href="${this.appUrl()}/pharmacy/queue" style="${this.btnStyle('purple')}">
          Review Draft →
        </a>
      `),
    };
  }

  buildReorderDeadline(productName: string, daysLeft: number): { subject: string; html: string } {
    return {
      subject: `🕐 Order ${productName} within ${daysLeft} day${daysLeft !== 1 ? 's' : ''} to avoid stockout`,
      html: this.wrap(`
        <h2 style="color:#d97706">Reorder Deadline Alert</h2>
        <p>Based on your current stock and supplier lead times, you need to place an order for
        <strong>${productName}</strong> within <strong>${daysLeft} day${daysLeft !== 1 ? 's' : ''}</strong>
        to avoid running out.</p>
        <a href="${this.appUrl()}/pharmacy/eoq" style="${this.btnStyle('orange')}">
          View Schedule →
        </a>
      `),
    };
  }

  // ── Internal ───────────────────────────────────────────────────────────────

  private wrap(content: string): string {
    return `
      <!DOCTYPE html>
      <html>
      <body style="font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;max-width:580px;margin:0 auto;padding:24px;color:#111827">
        <div style="margin-bottom:24px">
          <span style="font-size:24px">💊</span>
          <strong style="font-size:18px;margin-left:8px;color:#1e40af">MediPulse</strong>
        </div>
        <div style="background:#f9fafb;border-radius:12px;padding:24px;border:1px solid #e5e7eb">
          ${content}
        </div>
        <p style="color:#9ca3af;font-size:11px;margin-top:16px;text-align:center">
          MediPulse · Healthcare Procurement Intelligence · You can manage notification preferences in your account settings.
        </p>
      </body>
      </html>
    `;
  }

  private btnStyle(color: string): string {
    const colors: Record<string, string> = {
      red:    '#dc2626', blue: '#1d4ed8', green: '#16a34a',
      purple: '#7c3aed', orange: '#d97706',
    };
    const bg = colors[color] ?? colors.blue;
    return `display:inline-block;background:${bg};color:white;padding:12px 24px;border-radius:8px;text-decoration:none;font-weight:600;margin-top:16px`;
  }

  private appUrl(): string {
    return this.config.get('FRONTEND_URL', 'https://app.medipulse.ai');
  }
}
